name: Carlot CI
on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout
      
      - name: Set up Python
        uses: actions/setup-python
        with:
          python-version-file: '.python-version'
          
      - name: Cache Python dependencies
        uses: actions/cache
        id: cache
        with:
          path: |
            venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}
          
      - name: Create venv and install deps
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python -m venv venv
          venv/bin/pip install -r requirements.txt
          venv/bin/pip install pylint coverage
  
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout
      
      - name: Set up Python
        uses: actions/setup-python
        with:
          python-version-file: '.python-version'
          
      - name: Restore cached dependencies
        uses: actions/cache
        with:
          path: |
            venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}
      
      - name: Run Pylint
        run: |
          find . -name "*.py" -not -path "./venv/*" > pylint_files.txt
          venv/bin/pylint --fail-under=5 $(cat pylint_files.txt)
  
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout
      
      - name: Set up Python
        uses: actions/setup-python
        with:
          python-version-file: '.python-version'
          
      - name: Restore cached dependencies
        uses: actions/cache
        with:
          path: |
            venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}
      
      - name: Create test directories
        run: |
          mkdir -p test-reports
          mkdir -p api-test-reports
      
      - name: Run Tests with Coverage
        run: |
          # Find and run test files
          for file in $(find . -name "test_*.py" -not -path "./venv/*"); do
            venv/bin/coverage run --append --omit "*/site-packages/*,*/dist-packages/*,venv/*" "$file"
          done
          
          # Generate coverage report
          venv/bin/coverage report
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            test-reports/
            api-test-reports/
  
  zip:
    name: Zip
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout
                
      - name: Upload source code
        uses: actions/upload-artifact
        with:
          name: carlot-build
          path: |
            **/*.py
